/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.ChargesApi
import io.conekta.model.ChargeOrderResponse
import io.conekta.model.ChargeRequest
import io.conekta.model.ChargeResponse
import io.conekta.model.ChargeUpdateRequest
import io.conekta.model.Error
import io.conekta.model.GetChargesResponse

class ChargesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargesApi
        //val apiInstance = ChargesApi()

        // to test getCharges
        should("test getCharges") {
            // uncomment below to test getCharges
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val limit : kotlin.Int = 56 // kotlin.Int | The numbers of items to return, the maximum value is 250
            //val search : kotlin.String = search_example // kotlin.String | General order search, e.g. by mail, reference etc.
            //val next : kotlin.String = next_example // kotlin.String | next page
            //val previous : kotlin.String = previous_example // kotlin.String | previous page
            //val result : GetChargesResponse = apiInstance.getCharges(acceptLanguage, xChildCompanyId, limit, search, next, previous)
            //result shouldBe ("TODO")
        }

        // to test ordersCreateCharge
        should("test ordersCreateCharge") {
            // uncomment below to test ordersCreateCharge
            //val id : kotlin.String = 6307a60c41de27127515a575 // kotlin.String | Identifier of the resource
            //val chargeRequest : ChargeRequest =  // ChargeRequest | requested field for a charge
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val result : ChargeOrderResponse = apiInstance.ordersCreateCharge(id, chargeRequest, acceptLanguage, xChildCompanyId)
            //result shouldBe ("TODO")
        }

        // to test updateCharge
        should("test updateCharge") {
            // uncomment below to test updateCharge
            //val id : kotlin.String = 6307a60c41de27127515a575 // kotlin.String | Identifier of the resource
            //val chargeUpdateRequest : ChargeUpdateRequest =  // ChargeUpdateRequest | requested field for update a charge
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val result : ChargeResponse = apiInstance.updateCharge(id, chargeUpdateRequest, acceptLanguage, xChildCompanyId)
            //result shouldBe ("TODO")
        }

    }
}
