/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.TaxesApi
import io.conekta.model.Error
import io.conekta.model.OrderTaxRequest
import io.conekta.model.UpdateOrderTaxRequest
import io.conekta.model.UpdateOrderTaxResponse

class TaxesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaxesApi
        //val apiInstance = TaxesApi()

        // to test ordersCreateTaxes
        should("test ordersCreateTaxes") {
            // uncomment below to test ordersCreateTaxes
            //val id : kotlin.String = 6307a60c41de27127515a575 // kotlin.String | Identifier of the resource
            //val orderTaxRequest : OrderTaxRequest =  // OrderTaxRequest | requested field for a taxes
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val result : UpdateOrderTaxResponse = apiInstance.ordersCreateTaxes(id, orderTaxRequest, acceptLanguage, xChildCompanyId)
            //result shouldBe ("TODO")
        }

        // to test ordersDeleteTaxes
        should("test ordersDeleteTaxes") {
            // uncomment below to test ordersDeleteTaxes
            //val id : kotlin.String = 6307a60c41de27127515a575 // kotlin.String | Identifier of the resource
            //val taxId : kotlin.String = tax_lin_2tQ974hSHcsdeSZHG // kotlin.String | identifier
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val result : UpdateOrderTaxResponse = apiInstance.ordersDeleteTaxes(id, taxId, acceptLanguage, xChildCompanyId)
            //result shouldBe ("TODO")
        }

        // to test ordersUpdateTaxes
        should("test ordersUpdateTaxes") {
            // uncomment below to test ordersUpdateTaxes
            //val id : kotlin.String = 6307a60c41de27127515a575 // kotlin.String | Identifier of the resource
            //val taxId : kotlin.String = tax_lin_2tQ974hSHcsdeSZHG // kotlin.String | identifier
            //val updateOrderTaxRequest : UpdateOrderTaxRequest =  // UpdateOrderTaxRequest | requested field for taxes
            //val acceptLanguage : kotlin.String = es // kotlin.String | Use for knowing which language to use
            //val xChildCompanyId : kotlin.String = 6441b6376b60c3a638da80af // kotlin.String | In the case of a holding company, the company id of the child company to which will process the request.
            //val result : UpdateOrderTaxResponse = apiInstance.ordersUpdateTaxes(id, taxId, updateOrderTaxRequest, acceptLanguage, xChildCompanyId)
            //result shouldBe ("TODO")
        }

    }
}
