/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param role 
 * @param description A name or brief explanation of what this api key is used for
 */


data class ApiKeyRequest (

    @SerializedName("role")
    val role: kotlin.String,

    /* A name or brief explanation of what this api key is used for */
    @SerializedName("description")
    val description: kotlin.String? = null

)

