/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param segment 
 * @param checkoutRequestId 
 * @param checkoutRequestType 
 * @param id 
 */


data class ChargeResponseChannel (

    @SerializedName("segment")
    val segment: kotlin.String? = null,

    @SerializedName("checkout_request_id")
    val checkoutRequestId: kotlin.String? = null,

    @SerializedName("checkout_request_type")
    val checkoutRequestType: kotlin.String? = null,

    @SerializedName("id")
    val id: kotlin.String? = null

)

