/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.conekta.model.PaymentMethodCardRequest
import io.conekta.model.PaymentMethodGeneralRequest

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type Type of payment method
 * @param cvc Card security code
 * @param expMonth Card expiration month
 * @param expYear Card expiration year
 * @param name Cardholder name
 * @param number Card number
 * @param expiresAt Method expiration date as unix timestamp
 * @param monthlyInstallments How many months without interest to apply, it can be 3, 6, 9, 12 or 18
 * @param tokenId 
 * @param paymentSourceId 
 * @param contractId Optional id sent to indicate the bank contract for recurrent card charges.
 */


data class ChargeRequestPaymentMethod (

    /* Type of payment method */
    @SerializedName("type")
    val type: kotlin.String,

    /* Card security code */
    @SerializedName("cvc")
    val cvc: kotlin.String,

    /* Card expiration month */
    @SerializedName("exp_month")
    val expMonth: kotlin.String,

    /* Card expiration year */
    @SerializedName("exp_year")
    val expYear: kotlin.String,

    /* Cardholder name */
    @SerializedName("name")
    val name: kotlin.String,

    /* Card number */
    @SerializedName("number")
    val number: kotlin.String,

    /* Method expiration date as unix timestamp */
    @SerializedName("expires_at")
    val expiresAt: kotlin.Long? = null,

    /* How many months without interest to apply, it can be 3, 6, 9, 12 or 18 */
    @SerializedName("monthly_installments")
    val monthlyInstallments: kotlin.Int? = null,

    @SerializedName("token_id")
    val tokenId: kotlin.String? = null,

    @SerializedName("payment_source_id")
    val paymentSourceId: kotlin.String? = null,

    /* Optional id sent to indicate the bank contract for recurrent card charges. */
    @SerializedName("contract_id")
    val contractId: kotlin.String? = null

)

