/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.conekta.model.CustomerShippingContactsAddress

import com.google.gson.annotations.SerializedName

/**
 * [Shipping](https://developers.conekta.com/v2.1.0/reference/createcustomershippingcontacts) details, required in case of sending a shipping. If we do not receive a shipping_contact on the order, the default shipping_contact of the customer will be used.
 *
 * @param address 
 * @param phone Phone contact
 * @param `receiver` Name of the person who will receive the order
 * @param betweenStreets The street names between which the order will be delivered.
 * @param parentId 
 * @param default 
 * @param deleted 
 * @param metadata Metadata associated with the shipping contact
 */


data class CustomerShippingContacts (

    @SerializedName("address")
    val address: CustomerShippingContactsAddress,

    /* Phone contact */
    @SerializedName("phone")
    val phone: kotlin.String? = null,

    /* Name of the person who will receive the order */
    @SerializedName("receiver")
    val `receiver`: kotlin.String? = null,

    /* The street names between which the order will be delivered. */
    @SerializedName("between_streets")
    val betweenStreets: kotlin.String? = null,

    @SerializedName("parent_id")
    val parentId: kotlin.String? = null,

    @SerializedName("default")
    val default: kotlin.Boolean? = null,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean? = null,

    /* Metadata associated with the shipping contact */
    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

