/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * It is a parameter that allows to identify in the response, the type of event that is being generated.
 *
 * Values: webhook_ping,orderPeriodPaid,orderPeriodExpired,orderPeriodCanceled,orderPeriodPending_payment
 */

enum class EventTypes(val value: kotlin.String) {

    @SerializedName(value = "webhook_ping")
    webhook_ping("webhook_ping"),

    @SerializedName(value = "order.paid")
    orderPeriodPaid("order.paid"),

    @SerializedName(value = "order.expired")
    orderPeriodExpired("order.expired"),

    @SerializedName(value = "order.canceled")
    orderPeriodCanceled("order.canceled"),

    @SerializedName(value = "order.pending_payment")
    orderPeriodPending_payment("order.pending_payment");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EventTypes) "$data" else null

        /**
         * Returns a valid [EventTypes] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EventTypes? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

