/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.conekta.model.ChargeResponseChannel
import io.conekta.model.OrderFiscalEntityResponse
import io.conekta.model.OrderNextActionResponse
import io.conekta.model.OrderResponseCharges
import io.conekta.model.OrderResponseCheckout
import io.conekta.model.OrderResponseCustomerInfo
import io.conekta.model.OrderResponseDiscountLines
import io.conekta.model.OrderResponseProducts
import io.conekta.model.OrderResponseShippingContact

import com.google.gson.annotations.SerializedName

/**
 * order response
 *
 * @param amount The total amount to be collected in cents
 * @param amountRefunded The total amount refunded in cents
 * @param channel 
 * @param charges 
 * @param checkout 
 * @param createdAt The time at which the object was created in seconds since the Unix epoch
 * @param currency The three-letter ISO 4217 currency code. The currency of the order.
 * @param customerInfo 
 * @param discountLines 
 * @param fiscalEntity 
 * @param id 
 * @param isRefundable 
 * @param lineItems 
 * @param livemode Whether the object exists in live mode or test mode
 * @param metadata Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
 * @param nextAction 
 * @param `object` String representing the object’s type. Objects of the same type share the same value.
 * @param paymentStatus The payment status of the order.
 * @param processingMode Indicates the processing mode for the order, either ecommerce, recurrent or validation.
 * @param shippingContact 
 * @param updatedAt The time at which the object was last updated in seconds since the Unix epoch
 */


data class OrderResponse (

    /* The total amount to be collected in cents */
    @SerializedName("amount")
    val amount: kotlin.Int? = null,

    /* The total amount refunded in cents */
    @SerializedName("amount_refunded")
    val amountRefunded: kotlin.Int? = null,

    @SerializedName("channel")
    val channel: ChargeResponseChannel? = null,

    @SerializedName("charges")
    val charges: OrderResponseCharges? = null,

    @SerializedName("checkout")
    val checkout: OrderResponseCheckout? = null,

    /* The time at which the object was created in seconds since the Unix epoch */
    @SerializedName("created_at")
    val createdAt: kotlin.Long? = null,

    /* The three-letter ISO 4217 currency code. The currency of the order. */
    @SerializedName("currency")
    val currency: kotlin.String? = null,

    @SerializedName("customer_info")
    val customerInfo: OrderResponseCustomerInfo? = null,

    @SerializedName("discount_lines")
    val discountLines: OrderResponseDiscountLines? = null,

    @SerializedName("fiscal_entity")
    val fiscalEntity: OrderFiscalEntityResponse? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("is_refundable")
    val isRefundable: kotlin.Boolean? = null,

    @SerializedName("line_items")
    val lineItems: OrderResponseProducts? = null,

    /* Whether the object exists in live mode or test mode */
    @SerializedName("livemode")
    val livemode: kotlin.Boolean? = null,

    /* Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. */
    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @SerializedName("next_action")
    val nextAction: OrderNextActionResponse? = null,

    /* String representing the object’s type. Objects of the same type share the same value. */
    @SerializedName("object")
    val `object`: kotlin.String? = null,

    /* The payment status of the order. */
    @SerializedName("payment_status")
    val paymentStatus: kotlin.String? = null,

    /* Indicates the processing mode for the order, either ecommerce, recurrent or validation. */
    @SerializedName("processing_mode")
    val processingMode: kotlin.String? = null,

    @SerializedName("shipping_contact")
    val shippingContact: OrderResponseShippingContact? = null,

    /* The time at which the object was last updated in seconds since the Unix epoch */
    @SerializedName("updated_at")
    val updatedAt: kotlin.Long? = null

)

