/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param amount Shipping amount in cents
 * @param carrier Carrier name for the shipment
 * @param trackingNumber Tracking number can be used to track the shipment
 * @param method Method of shipment
 * @param metadata Hash where the user can send additional information for each 'shipping'.
 */


data class ShippingRequest (

    /* Shipping amount in cents */
    @SerializedName("amount")
    val amount: kotlin.Long,

    /* Carrier name for the shipment */
    @SerializedName("carrier")
    val carrier: kotlin.String? = null,

    /* Tracking number can be used to track the shipment */
    @SerializedName("tracking_number")
    val trackingNumber: kotlin.String? = null,

    /* Method of shipment */
    @SerializedName("method")
    val method: kotlin.String? = null,

    /* Hash where the user can send additional information for each 'shipping'. */
    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

