/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * You can modify the subscription to change the plan used by your customers.
 *
 * @param planId 
 * @param cardId 
 * @param trialEnd 
 */


data class SubscriptionUpdateRequest (

    @SerializedName("plan_id")
    val planId: kotlin.String? = null,

    @SerializedName("card_id")
    val cardId: kotlin.String? = null,

    @SerializedName("trial_end")
    val trialEnd: kotlin.Int? = null

)

