/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cvc It is a value that allows identifying the security code of the card.
 * @param expMonth It is a value that allows identifying the expiration month of the card.
 * @param expYear It is a value that allows identifying the expiration year of the card.
 * @param name It is a value that allows identifying the name of the cardholder.
 * @param number It is a value that allows identifying the number of the card.
 * @param deviceFingerprint It is a value that allows identifying the device fingerprint.
 */


data class TokenCard (

    /* It is a value that allows identifying the security code of the card. */
    @SerializedName("cvc")
    val cvc: kotlin.String,

    /* It is a value that allows identifying the expiration month of the card. */
    @SerializedName("exp_month")
    val expMonth: kotlin.String,

    /* It is a value that allows identifying the expiration year of the card. */
    @SerializedName("exp_year")
    val expYear: kotlin.String,

    /* It is a value that allows identifying the name of the cardholder. */
    @SerializedName("name")
    val name: kotlin.String,

    /* It is a value that allows identifying the number of the card. */
    @SerializedName("number")
    val number: kotlin.String,

    /* It is a value that allows identifying the device fingerprint. */
    @SerializedName("device_fingerprint")
    val deviceFingerprint: kotlin.String? = null

)

