/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * create new taxes for an existing order
 *
 * @param amount The amount to be collected for tax in cents
 * @param description description or tax's name
 * @param metadata 
 */


data class UpdateOrderTaxRequest (

    /* The amount to be collected for tax in cents */
    @SerializedName("amount")
    val amount: kotlin.Long? = null,

    /* description or tax's name */
    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

