/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param failedAttempts 
 * @param id 
 * @param lastAttemptedAt 
 * @param lastHttpResponseStatus 
 * @param `object` 
 * @param responseData 
 * @param url 
 */


data class WebhookLog (

    @SerializedName("failed_attempts")
    val failedAttempts: kotlin.Int? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("last_attempted_at")
    val lastAttemptedAt: kotlin.Int? = null,

    @SerializedName("last_http_response_status")
    val lastHttpResponseStatus: kotlin.Int? = null,

    @SerializedName("object")
    val `object`: kotlin.String? = null,

    @SerializedName("response_data")
    val responseData: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @SerializedName("url")
    val url: java.net.URI? = null

)

