/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.ChargeRequest
import io.conekta.model.ChargeRequestPaymentMethod

class ChargeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargeRequest
        //val modelInstance = ChargeRequest()

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `amount` - Amount to be charged in cents
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `referenceId` - Custom reference to add to the charge
        should("test referenceId") {
            // uncomment below to test the property
            //modelInstance.referenceId shouldBe ("TODO")
        }

    }
}
