/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.ChargeResponse
import io.conekta.model.ChargeResponseChannel
import io.conekta.model.ChargeResponsePaymentMethod
import io.conekta.model.ChargeResponseRefunds

class ChargeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargeResponse
        //val modelInstance = ChargeResponse()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `channel`
        should("test channel") {
            // uncomment below to test the property
            //modelInstance.channel shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `customerId`
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `deviceFingerprint`
        should("test deviceFingerprint") {
            // uncomment below to test the property
            //modelInstance.deviceFingerprint shouldBe ("TODO")
        }

        // to test the property `failureCode`
        should("test failureCode") {
            // uncomment below to test the property
            //modelInstance.failureCode shouldBe ("TODO")
        }

        // to test the property `failureMessage`
        should("test failureMessage") {
            // uncomment below to test the property
            //modelInstance.failureMessage shouldBe ("TODO")
        }

        // to test the property `id` - Charge ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `livemode` - Whether the charge was made in live mode or not
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `orderId` - Order ID
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `paidAt` - Payment date
        should("test paidAt") {
            // uncomment below to test the property
            //modelInstance.paidAt shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `referenceId` - Reference ID of the charge
        should("test referenceId") {
            // uncomment below to test the property
            //modelInstance.referenceId shouldBe ("TODO")
        }

        // to test the property `refunds`
        should("test refunds") {
            // uncomment below to test the property
            //modelInstance.refunds shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
