/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.CheckoutOrderTemplate
import io.conekta.model.CheckoutOrderTemplateCustomerInfo
import io.conekta.model.Product

class CheckoutOrderTemplateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutOrderTemplate
        //val modelInstance = CheckoutOrderTemplate()

        // to test the property `currency` - It is the currency in which the order will be created. It must be a valid ISO 4217 currency code.
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `lineItems` - They are the products to buy. Each contains the \"unit price\" and \"quantity\" parameters that are used to calculate the total amount of the order.
        should("test lineItems") {
            // uncomment below to test the property
            //modelInstance.lineItems shouldBe ("TODO")
        }

        // to test the property `customerInfo`
        should("test customerInfo") {
            // uncomment below to test the property
            //modelInstance.customerInfo shouldBe ("TODO")
        }

        // to test the property `metadata` - It is a set of key-value pairs that you can attach to the order. It can be used to store additional information about the order in a structured format.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
