/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.CustomerFiscalEntitiesRequest
import io.conekta.model.CustomerAddress

class CustomerFiscalEntitiesRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerFiscalEntitiesRequest
        //val modelInstance = CustomerFiscalEntitiesRequest()

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `taxId`
        should("test taxId") {
            // uncomment below to test the property
            //modelInstance.taxId shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `companyName`
        should("test companyName") {
            // uncomment below to test the property
            //modelInstance.companyName shouldBe ("TODO")
        }

    }
}
