/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.CustomerAddress

class CustomerAddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerAddress
        //val modelInstance = CustomerAddress()

        // to test the property `street1`
        should("test street1") {
            // uncomment below to test the property
            //modelInstance.street1 shouldBe ("TODO")
        }

        // to test the property `postalCode`
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `street2`
        should("test street2") {
            // uncomment below to test the property
            //modelInstance.street2 shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `country` - this field follows the [ISO 3166-1 alpha-2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `residential`
        should("test residential") {
            // uncomment below to test the property
            //modelInstance.residential shouldBe ("TODO")
        }

        // to test the property `externalNumber`
        should("test externalNumber") {
            // uncomment below to test the property
            //modelInstance.externalNumber shouldBe ("TODO")
        }

    }
}
