/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.CustomerPaymentMethodsData
import io.conekta.model.PaymentMethodCardResponse
import io.conekta.model.PaymentMethodCashResponse
import io.conekta.model.PaymentMethodSpeiRecurrent

class CustomerPaymentMethodsDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerPaymentMethodsData
        //val modelInstance = CustomerPaymentMethodsData()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `parentId`
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

        // to test the property `reference`
        should("test reference") {
            // uncomment below to test the property
            //modelInstance.reference shouldBe ("TODO")
        }

        // to test the property `barcode`
        should("test barcode") {
            // uncomment below to test the property
            //modelInstance.barcode shouldBe ("TODO")
        }

        // to test the property `barcodeUrl`
        should("test barcodeUrl") {
            // uncomment below to test the property
            //modelInstance.barcodeUrl shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `last4`
        should("test last4") {
            // uncomment below to test the property
            //modelInstance.last4 shouldBe ("TODO")
        }

        // to test the property `bin`
        should("test bin") {
            // uncomment below to test the property
            //modelInstance.bin shouldBe ("TODO")
        }

        // to test the property `cardType`
        should("test cardType") {
            // uncomment below to test the property
            //modelInstance.cardType shouldBe ("TODO")
        }

        // to test the property `expMonth`
        should("test expMonth") {
            // uncomment below to test the property
            //modelInstance.expMonth shouldBe ("TODO")
        }

        // to test the property `expYear`
        should("test expYear") {
            // uncomment below to test the property
            //modelInstance.expYear shouldBe ("TODO")
        }

        // to test the property `brand`
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `default`
        should("test default") {
            // uncomment below to test the property
            //modelInstance.default shouldBe ("TODO")
        }

        // to test the property `visibleOnCheckout`
        should("test visibleOnCheckout") {
            // uncomment below to test the property
            //modelInstance.visibleOnCheckout shouldBe ("TODO")
        }

        // to test the property `paymentSourceStatus`
        should("test paymentSourceStatus") {
            // uncomment below to test the property
            //modelInstance.paymentSourceStatus shouldBe ("TODO")
        }

    }
}
