/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.OrderUpdateRequestCustomerInfo
import io.conekta.model.CustomerInfo
import io.conekta.model.CustomerInfoJustCustomerId

class OrderUpdateRequestCustomerInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderUpdateRequestCustomerInfo
        //val modelInstance = OrderUpdateRequestCustomerInfo()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `customerId`
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `corporate`
        should("test corporate") {
            // uncomment below to test the property
            //modelInstance.corporate shouldBe ("TODO")
        }

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

    }
}
