/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PaymentMethodBankTransfer

class PaymentMethodBankTransferTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethodBankTransfer
        //val modelInstance = PaymentMethodBankTransfer()

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `bank`
        should("test bank") {
            // uncomment below to test the property
            //modelInstance.bank shouldBe ("TODO")
        }

        // to test the property `clabe`
        should("test clabe") {
            // uncomment below to test the property
            //modelInstance.clabe shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `executedAt`
        should("test executedAt") {
            // uncomment below to test the property
            //modelInstance.executedAt shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `issuingAccountBank`
        should("test issuingAccountBank") {
            // uncomment below to test the property
            //modelInstance.issuingAccountBank shouldBe ("TODO")
        }

        // to test the property `issuingAccountNumber`
        should("test issuingAccountNumber") {
            // uncomment below to test the property
            //modelInstance.issuingAccountNumber shouldBe ("TODO")
        }

        // to test the property `issuingAccountHolderName`
        should("test issuingAccountHolderName") {
            // uncomment below to test the property
            //modelInstance.issuingAccountHolderName shouldBe ("TODO")
        }

        // to test the property `issuingAccountTaxId`
        should("test issuingAccountTaxId") {
            // uncomment below to test the property
            //modelInstance.issuingAccountTaxId shouldBe ("TODO")
        }

        // to test the property `paymentAttempts`
        should("test paymentAttempts") {
            // uncomment below to test the property
            //modelInstance.paymentAttempts shouldBe ("TODO")
        }

        // to test the property `receivingAccountHolderName`
        should("test receivingAccountHolderName") {
            // uncomment below to test the property
            //modelInstance.receivingAccountHolderName shouldBe ("TODO")
        }

        // to test the property `receivingAccountNumber`
        should("test receivingAccountNumber") {
            // uncomment below to test the property
            //modelInstance.receivingAccountNumber shouldBe ("TODO")
        }

        // to test the property `receivingAccountBank`
        should("test receivingAccountBank") {
            // uncomment below to test the property
            //modelInstance.receivingAccountBank shouldBe ("TODO")
        }

        // to test the property `receivingAccountTaxId`
        should("test receivingAccountTaxId") {
            // uncomment below to test the property
            //modelInstance.receivingAccountTaxId shouldBe ("TODO")
        }

        // to test the property `referenceNumber`
        should("test referenceNumber") {
            // uncomment below to test the property
            //modelInstance.referenceNumber shouldBe ("TODO")
        }

        // to test the property `trackingCode`
        should("test trackingCode") {
            // uncomment below to test the property
            //modelInstance.trackingCode shouldBe ("TODO")
        }

    }
}
