/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PaymentMethodCash

class PaymentMethodCashTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethodCash
        //val modelInstance = PaymentMethodCash()

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `authCode`
        should("test authCode") {
            // uncomment below to test the property
            //modelInstance.authCode shouldBe ("TODO")
        }

        // to test the property `cashierId`
        should("test cashierId") {
            // uncomment below to test the property
            //modelInstance.cashierId shouldBe ("TODO")
        }

        // to test the property `reference`
        should("test reference") {
            // uncomment below to test the property
            //modelInstance.reference shouldBe ("TODO")
        }

        // to test the property `barcodeUrl`
        should("test barcodeUrl") {
            // uncomment below to test the property
            //modelInstance.barcodeUrl shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `serviceName`
        should("test serviceName") {
            // uncomment below to test the property
            //modelInstance.serviceName shouldBe ("TODO")
        }

        // to test the property `store`
        should("test store") {
            // uncomment below to test the property
            //modelInstance.store shouldBe ("TODO")
        }

        // to test the property `storeName`
        should("test storeName") {
            // uncomment below to test the property
            //modelInstance.storeName shouldBe ("TODO")
        }

    }
}
