/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PaymentMethodCard

class PaymentMethodCardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethodCard
        //val modelInstance = PaymentMethodCard()

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `accountType` - Account type of the card
        should("test accountType") {
            // uncomment below to test the property
            //modelInstance.accountType shouldBe ("TODO")
        }

        // to test the property `authCode`
        should("test authCode") {
            // uncomment below to test the property
            //modelInstance.authCode shouldBe ("TODO")
        }

        // to test the property `brand` - Brand of the card
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `contractId` - Id sent for recurrent charges.
        should("test contractId") {
            // uncomment below to test the property
            //modelInstance.contractId shouldBe ("TODO")
        }

        // to test the property `country` - Country of the card
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `expMonth` - Expiration month of the card
        should("test expMonth") {
            // uncomment below to test the property
            //modelInstance.expMonth shouldBe ("TODO")
        }

        // to test the property `expYear` - Expiration year of the card
        should("test expYear") {
            // uncomment below to test the property
            //modelInstance.expYear shouldBe ("TODO")
        }

        // to test the property `fraudIndicators`
        should("test fraudIndicators") {
            // uncomment below to test the property
            //modelInstance.fraudIndicators shouldBe ("TODO")
        }

        // to test the property `issuer` - Issuer of the card
        should("test issuer") {
            // uncomment below to test the property
            //modelInstance.issuer shouldBe ("TODO")
        }

        // to test the property `last4` - Last 4 digits of the card
        should("test last4") {
            // uncomment below to test the property
            //modelInstance.last4 shouldBe ("TODO")
        }

        // to test the property `name` - Name of the cardholder
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
