/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PayoutOrderPayoutsItem

class PayoutOrderPayoutsItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayoutOrderPayoutsItem
        //val modelInstance = PayoutOrderPayoutsItem()

        // to test the property `amount` - The amount of the payout.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - The currency in which the payout is made.
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `id` - The id of the payout.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `livemode` - The live mode of the payout.
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property ``object`` - The object of the payout.
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `expiresAt` - The expiration date of the payout.
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `payoutOrderId` - The id of the payout order.
        should("test payoutOrderId") {
            // uncomment below to test the property
            //modelInstance.payoutOrderId shouldBe ("TODO")
        }

        // to test the property `status` - The status of the payout.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
