/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PlanResponse

class PlanResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlanResponse
        //val modelInstance = PlanResponse()

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `expiryCount`
        should("test expiryCount") {
            // uncomment below to test the property
            //modelInstance.expiryCount shouldBe ("TODO")
        }

        // to test the property `frequency`
        should("test frequency") {
            // uncomment below to test the property
            //modelInstance.frequency shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `interval`
        should("test interval") {
            // uncomment below to test the property
            //modelInstance.interval shouldBe ("TODO")
        }

        // to test the property `livemode`
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `trialPeriodDays`
        should("test trialPeriodDays") {
            // uncomment below to test the property
            //modelInstance.trialPeriodDays shouldBe ("TODO")
        }

    }
}
