/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.PlanUpdateRequest

class PlanUpdateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlanUpdateRequest
        //val modelInstance = PlanUpdateRequest()

        // to test the property `amount` - The amount in cents that will be charged on the interval specified.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - ISO 4217 for currencies, for the Mexican peso it is MXN/USD
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `expiryCount` - Number of repetitions of the frequency NUMBER OF CHARGES TO BE MADE, considering the interval and frequency, this evolves over time, but is subject to the expiration count.
        should("test expiryCount") {
            // uncomment below to test the property
            //modelInstance.expiryCount shouldBe ("TODO")
        }

        // to test the property `name` - The name of the plan.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
