/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.TokenCheckout

class TokenCheckoutTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenCheckout
        //val modelInstance = TokenCheckout()

        // to test the property `returnsControlOn` - It is a value that allows identifying the returns control on.
        should("test returnsControlOn") {
            // uncomment below to test the property
            //modelInstance.returnsControlOn shouldBe ("TODO")
        }

    }
}
