/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.TransfersResponse
import io.conekta.model.TransferMethodResponse

class TransfersResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransfersResponse
        //val modelInstance = TransfersResponse()

        // to test the property `amount` - Amount in cents of the transfer.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `createdAt` - Date and time of creation of the transfer.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `currency` - The currency of the transfer. It uses the 3-letter code of the [International Standard ISO 4217.](https://es.wikipedia.org/wiki/ISO_4217)
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `id` - Unique identifier of the transfer.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `livemode` - Indicates whether the transfer was created in live mode or test mode.
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property `method`
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

        // to test the property ``object`` - Object name, which is transfer.
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `statementDescription` - Description of the transfer.
        should("test statementDescription") {
            // uncomment below to test the property
            //modelInstance.statementDescription shouldBe ("TODO")
        }

        // to test the property `statementReference` - Reference number of the transfer.
        should("test statementReference") {
            // uncomment below to test the property
            //modelInstance.statementReference shouldBe ("TODO")
        }

        // to test the property `status` - Code indicating transfer status.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
