/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.conekta.model.WebhookResponse

class WebhookResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebhookResponse
        //val modelInstance = WebhookResponse()

        // to test the property `deleted`
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `developmentEnabled`
        should("test developmentEnabled") {
            // uncomment below to test the property
            //modelInstance.developmentEnabled shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `livemode`
        should("test livemode") {
            // uncomment below to test the property
            //modelInstance.livemode shouldBe ("TODO")
        }

        // to test the property ``object``
        should("test `object`") {
            // uncomment below to test the property
            //modelInstance.`object` shouldBe ("TODO")
        }

        // to test the property `productionEnabled`
        should("test productionEnabled") {
            // uncomment below to test the property
            //modelInstance.productionEnabled shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `subscribedEvents`
        should("test subscribedEvents") {
            // uncomment below to test the property
            //modelInstance.subscribedEvents shouldBe ("TODO")
        }

        // to test the property `synchronous`
        should("test synchronous") {
            // uncomment below to test the property
            //modelInstance.synchronous shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
