/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.conekta;

import io.conekta.ApiInvoker;
import io.conekta.ApiException;
import io.conekta.Pair;

import io.conekta.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import io.conekta.model.ChargeOrderResponse;
import io.conekta.model.ChargeRequest;
import io.conekta.model.ChargeResponse;
import io.conekta.model.ChargeUpdateRequest;
import io.conekta.model.Error;
import io.conekta.model.GetChargesResponse;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class ChargesApi {
  String basePath = "https://api.conekta.io";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
  * Get A List of Charges
  * 
   * @param acceptLanguage Use for knowing which language to use
   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.
   * @param limit The numbers of items to return, the maximum value is 250
   * @param search General order search, e.g. by mail, reference etc.
   * @param next next page
   * @param previous previous page
   * @return GetChargesResponse
  */
  public GetChargesResponse getCharges (String acceptLanguage, String xChildCompanyId, Integer limit, String search, String next, String previous) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;

    // create path and map variables
    String path = "/charges";

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    queryParams.addAll(ApiInvoker.parameterToPairs("", "limit", limit));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "search", search));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "next", next));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "previous", previous));
    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));
    String[] contentTypes = {
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (GetChargesResponse) ApiInvoker.deserialize(localVarResponse, "", GetChargesResponse.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Get A List of Charges
   * 
   * @param acceptLanguage Use for knowing which language to use   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.   * @param limit The numbers of items to return, the maximum value is 250   * @param search General order search, e.g. by mail, reference etc.   * @param next next page   * @param previous previous page
  */
  public void getCharges (String acceptLanguage, String xChildCompanyId, Integer limit, String search, String next, String previous, final Response.Listener<GetChargesResponse> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;


    // create path and map variables
    String path = "/charges".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();

    queryParams.addAll(ApiInvoker.parameterToPairs("", "limit", limit));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "search", search));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "next", next));
    queryParams.addAll(ApiInvoker.parameterToPairs("", "previous", previous));

    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));

    String[] contentTypes = {
      
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((GetChargesResponse) ApiInvoker.deserialize(localVarResponse,  "", GetChargesResponse.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Create charge
  * Create charge for an existing orden
   * @param id Identifier of the resource
   * @param chargeRequest requested field for a charge
   * @param acceptLanguage Use for knowing which language to use
   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.
   * @return ChargeOrderResponse
  */
  public ChargeOrderResponse ordersCreateCharge (String id, ChargeRequest chargeRequest, String acceptLanguage, String xChildCompanyId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = chargeRequest;
    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling ordersCreateCharge",
        new ApiException(400, "Missing the required parameter 'id' when calling ordersCreateCharge"));
    }
    // verify the required parameter 'chargeRequest' is set
    if (chargeRequest == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chargeRequest' when calling ordersCreateCharge",
        new ApiException(400, "Missing the required parameter 'chargeRequest' when calling ordersCreateCharge"));
    }

    // create path and map variables
    String path = "/orders/{id}/charges".replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ChargeOrderResponse) ApiInvoker.deserialize(localVarResponse, "", ChargeOrderResponse.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Create charge
   * Create charge for an existing orden
   * @param id Identifier of the resource   * @param chargeRequest requested field for a charge   * @param acceptLanguage Use for knowing which language to use   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.
  */
  public void ordersCreateCharge (String id, ChargeRequest chargeRequest, String acceptLanguage, String xChildCompanyId, final Response.Listener<ChargeOrderResponse> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = chargeRequest;

    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling ordersCreateCharge",
        new ApiException(400, "Missing the required parameter 'id' when calling ordersCreateCharge"));
    }
    // verify the required parameter 'chargeRequest' is set
    if (chargeRequest == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chargeRequest' when calling ordersCreateCharge",
        new ApiException(400, "Missing the required parameter 'chargeRequest' when calling ordersCreateCharge"));
    }

    // create path and map variables
    String path = "/orders/{id}/charges".replaceAll("\\{format\\}","json").replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();


    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));

    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ChargeOrderResponse) ApiInvoker.deserialize(localVarResponse,  "", ChargeOrderResponse.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * Update a charge
  * 
   * @param id Identifier of the resource
   * @param chargeUpdateRequest requested field for update a charge
   * @param acceptLanguage Use for knowing which language to use
   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.
   * @return ChargeResponse
  */
  public ChargeResponse updateCharge (String id, ChargeUpdateRequest chargeUpdateRequest, String acceptLanguage, String xChildCompanyId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = chargeUpdateRequest;
    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling updateCharge",
        new ApiException(400, "Missing the required parameter 'id' when calling updateCharge"));
    }
    // verify the required parameter 'chargeUpdateRequest' is set
    if (chargeUpdateRequest == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chargeUpdateRequest' when calling updateCharge",
        new ApiException(400, "Missing the required parameter 'chargeUpdateRequest' when calling updateCharge"));
    }

    // create path and map variables
    String path = "/charges/{id}".replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (ChargeResponse) ApiInvoker.deserialize(localVarResponse, "", ChargeResponse.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * Update a charge
   * 
   * @param id Identifier of the resource   * @param chargeUpdateRequest requested field for update a charge   * @param acceptLanguage Use for knowing which language to use   * @param xChildCompanyId In the case of a holding company, the company id of the child company to which will process the request.
  */
  public void updateCharge (String id, ChargeUpdateRequest chargeUpdateRequest, String acceptLanguage, String xChildCompanyId, final Response.Listener<ChargeResponse> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = chargeUpdateRequest;

    // verify the required parameter 'id' is set
    if (id == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'id' when calling updateCharge",
        new ApiException(400, "Missing the required parameter 'id' when calling updateCharge"));
    }
    // verify the required parameter 'chargeUpdateRequest' is set
    if (chargeUpdateRequest == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'chargeUpdateRequest' when calling updateCharge",
        new ApiException(400, "Missing the required parameter 'chargeUpdateRequest' when calling updateCharge"));
    }

    // create path and map variables
    String path = "/charges/{id}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "id" + "\\}", apiInvoker.escapeString(id.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();


    headerParams.put("Accept-Language", ApiInvoker.parameterToString(acceptLanguage));
    headerParams.put("X-Child-Company-Id", ApiInvoker.parameterToString(xChildCompanyId));

    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] { "bearerAuth" };

    try {
      apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((ChargeResponse) ApiInvoker.deserialize(localVarResponse,  "", ChargeResponse.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
}
