/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.conekta.model.BalanceCommonField

import com.google.gson.annotations.SerializedName

/**
 * balance model
 *
 * @param available The balance's available
 * @param cashoutRetentionAmount The balance's cashout retention amount
 * @param conektaRetention The balance's conekta retention
 * @param gateway The balance's gateway
 * @param pending The balance's pending
 * @param retained The balance's retained
 * @param retentionAmount The balance's retention amount
 * @param targetCollateralAmount The balance's target collateral amount
 * @param targetRetentionAmount The balance's target retention amount
 * @param temporarilyRetained The balance's temporarily retained
 */


data class BalanceResponse (

    /* The balance's available */
    @SerializedName("available")
    val available: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's cashout retention amount */
    @SerializedName("cashout_retention_amount")
    val cashoutRetentionAmount: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's conekta retention */
    @SerializedName("conekta_retention")
    val conektaRetention: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's gateway */
    @SerializedName("gateway")
    val gateway: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's pending */
    @SerializedName("pending")
    val pending: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's retained */
    @SerializedName("retained")
    val retained: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's retention amount */
    @SerializedName("retention_amount")
    val retentionAmount: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's target collateral amount */
    @SerializedName("target_collateral_amount")
    val targetCollateralAmount: kotlin.Any? = null,

    /* The balance's target retention amount */
    @SerializedName("target_retention_amount")
    val targetRetentionAmount: kotlin.collections.List<BalanceCommonField>? = null,

    /* The balance's temporarily retained */
    @SerializedName("temporarily_retained")
    val temporarilyRetained: kotlin.collections.List<BalanceCommonField>? = null

)

