/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model

import io.conekta.model.CheckoutOrderTemplate

import com.google.gson.annotations.SerializedName

/**
 * It is a sub-resource of the Order model that can be stipulated in order to configure its corresponding checkout
 *
 * @param allowedPaymentMethods Those are the payment methods that will be available for the link
 * @param expiresAt It is the time when the link will expire. It is expressed in seconds since the Unix epoch. The valid range is from 2 to 365 days (the valid range will be taken from the next day of the creation date at 00:01 hrs) 
 * @param name Reason for charge
 * @param orderTemplate 
 * @param recurrent false: single use. true: multiple payments
 * @param type It is the type of link that will be created. It must be a valid type.
 * @param monthlyInstallmentsEnabled This flag allows you to specify if months without interest will be active.
 * @param monthlyInstallmentsOptions This field allows you to specify the number of months without interest.
 * @param needsShippingContact This flag allows you to fill in the shipping information at checkout.
 * @param onDemandEnabled This flag allows you to specify if the link will be on demand.
 * @param paymentsLimitCount It is the number of payments that can be made through the link.
 */


data class Checkout (

    /* Those are the payment methods that will be available for the link */
    @SerializedName("allowed_payment_methods")
    val allowedPaymentMethods: kotlin.collections.List<kotlin.String>,

    /* It is the time when the link will expire. It is expressed in seconds since the Unix epoch. The valid range is from 2 to 365 days (the valid range will be taken from the next day of the creation date at 00:01 hrs)  */
    @SerializedName("expires_at")
    val expiresAt: kotlin.Long,

    /* Reason for charge */
    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("order_template")
    val orderTemplate: CheckoutOrderTemplate,

    /* false: single use. true: multiple payments */
    @SerializedName("recurrent")
    val recurrent: kotlin.Boolean,

    /* It is the type of link that will be created. It must be a valid type. */
    @SerializedName("type")
    val type: kotlin.String,

    /* This flag allows you to specify if months without interest will be active. */
    @SerializedName("monthly_installments_enabled")
    val monthlyInstallmentsEnabled: kotlin.Boolean? = null,

    /* This field allows you to specify the number of months without interest. */
    @SerializedName("monthly_installments_options")
    val monthlyInstallmentsOptions: kotlin.collections.List<kotlin.Int>? = null,

    /* This flag allows you to fill in the shipping information at checkout. */
    @SerializedName("needs_shipping_contact")
    val needsShippingContact: kotlin.Boolean? = null,

    /* This flag allows you to specify if the link will be on demand. */
    @SerializedName("on_demand_enabled")
    val onDemandEnabled: kotlin.Boolean? = null,

    /* It is the number of payments that can be made through the link. */
    @SerializedName("payments_limit_count")
    val paymentsLimitCount: kotlin.Int? = null

)

