/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * plans model
 *
 * @param amount 
 * @param createdAt 
 * @param currency 
 * @param expiryCount 
 * @param frequency 
 * @param id 
 * @param interval 
 * @param livemode 
 * @param name 
 * @param `object` 
 * @param trialPeriodDays 
 */


data class PlanResponse (

    @SerializedName("amount")
    val amount: kotlin.Int? = null,

    @SerializedName("created_at")
    val createdAt: kotlin.Long? = null,

    @SerializedName("currency")
    val currency: kotlin.String? = null,

    @SerializedName("expiry_count")
    val expiryCount: kotlin.Int? = null,

    @SerializedName("frequency")
    val frequency: kotlin.Int? = null,

    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("interval")
    val interval: kotlin.String? = null,

    @SerializedName("livemode")
    val livemode: kotlin.Boolean? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("object")
    val `object`: kotlin.String? = null,

    @SerializedName("trial_period_days")
    val trialPeriodDays: kotlin.Int? = null

)

