/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.conekta.model


import com.google.gson.annotations.SerializedName

/**
 * webhook keys model
 *
 * @param active Indicates if the webhook key is active
 * @param createdAt Unix timestamp in seconds with the creation date of the webhook key
 * @param deleted Indicates if the webhook key is deleted
 * @param id Unique identifier of the webhook key
 * @param livemode Indicates if the webhook key is in live mode
 * @param `object` Object name, value is webhook_key
 */


data class WebhookKeyDeleteResponse (

    /* Indicates if the webhook key is active */
    @SerializedName("active")
    val active: kotlin.Boolean? = null,

    /* Unix timestamp in seconds with the creation date of the webhook key */
    @SerializedName("created_at")
    val createdAt: kotlin.Long? = null,

    /* Indicates if the webhook key is deleted */
    @SerializedName("deleted")
    val deleted: kotlin.Boolean? = null,

    /* Unique identifier of the webhook key */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* Indicates if the webhook key is in live mode */
    @SerializedName("livemode")
    val livemode: kotlin.Boolean? = null,

    /* Object name, value is webhook_key */
    @SerializedName("object")
    val `object`: kotlin.String? = null

)

