name: Build

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Run Mockoon CLI
      uses: mockoon/cli-action@v2
      with:
        version: 'latest'
        data-file: 'https://raw.githubusercontent.com/conekta/openapi/main/mocks/conekta_api.json'
        port: 3000
    - name: Build
      run: |
        ./gradlew clean build 
    - name: test
      run: |
        ./gradlew  test
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
